FROM postgres:latest

WORKDIR /c/Users/anthony/PycharmProjects/TicTacToe

# TODO update to load db with table
COPY template_ttt_db_plain_text.sql /docker-entrypoint-initdb.d/init.sql

RUN chmod +x /docker-entrypoint-initdb.d/init.sql
