FROM postgres:latest

WORKDIR /c/Users/anthony/PycharmProjects/SAI

# TODO update to load db with table
#COPY tools/template_sai_db_plain_text.sql /docker-entrypoint-initdb.d/init.sql

#RUN chmod +x /docker-entrypoint-initdb.d/init.sql
